# Generated by Django 4.1.6 on 2023-05-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0003_remove_client_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='first_draft_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_hour',
        ),
        migrations.AddField(
            model_name='project',
            name='alert_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='pid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataManagement.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=100),
        ),
    ]
