# Generated by Django 4.1.6 on 2023-05-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
        ('dataManagement', '0004_rename_status_project_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to='userManagement.employee'),
        ),
    ]
