# Generated by Django 4.1.6 on 2023-05-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0005_alter_project_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='active',
            new_name='status',
        ),
    ]
