# Generated by Django 4.1.6 on 2023-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0006_rename_active_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
