# Generated by Django 4.1.6 on 2023-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0009_projectapisetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapisetting',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectapisetting',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
