# Generated by Django 4.1.6 on 2023-05-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('api', models.BooleanField(default=True)),
                ('parameter', models.BooleanField(default=True)),
            ],
        ),
    ]
